name: duckcart_osama
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.6
  shared_preferences: ^2.0.13
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  currency_picker: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
